{{#graph}}
  "model": "secdeva/graphModels/dataflow",
  "view": "secdeva/graphViews/entity"
{{/graph}}

== Composite elements

[TIP]
====
To add a dataflow to or from this data store, click the link symbol in the top level tool bar. Optionally, if you want to model interfaces as well, you can create an interface and link any incoming dataflows to the interface.
====

{{#createCards}}
  "buttonLabel": "Create an interface",
  "template": "secdeva/templates/interface"
{{/createCards}}

{{#createCards}}
    "buttonLabel": "Create a trust boundary",
    "template": "secdeva/templates/trustBoundary"
{{/createCards}}

{{#createCards}}
  "buttonLabel": "Create an external entity",
  "template": "secdeva/templates/external"
{{/createCards}}

{{#createCards}}
  "buttonLabel": "Create a person",
  "template": "secdeva/templates/person"
{{/createCards}}

{{#createCards}}
  "buttonLabel": "Create a process",
  "template": "secdeva/templates/process"
{{/createCards}}

{{#createCards}}
  "buttonLabel": "Create a data store",
  "template": "secdeva/templates/dataStore"
{{/createCards}}

== Interfaces

{{#report}}
  "name": "secdeva/reports/entityInterfaces"
{{/report}}

== Security issues

{{#report}}
  "name": "secdeva/reports/createThreat"
{{/report}}

{{#report}}
  "name": "secdeva/reports/securityIssueList"
{{/report}}

== Decisions and design specifications

Document a technical decision or create a design specification.

{{#createCards}}
  "buttonLabel": "Create a decision",
  "template": "base/templates/decision"
{{/createCards}}

{{#createCards}}
  "buttonLabel": "Create a specification",
  "template": "secdeva/templates/designSpecification"
{{/createCards}}

{{#report}}
  "name": "base/reports/childrenTable",
  "cardType": "base/cardTypes/decision",
  "tableCaption": "Decisions"
{{/report}}

{{#report}}
  "name": "base/reports/childrenTable",
  "cardType": "base/cardTypes/controlledDocument",
  "tableCaption": "Specifications"
{{/report}}