== Introduction

This document is a review of fuzz testing.

=== Scope of testing

#TODO: describe scope#

== Goals of fuzz testing

Fuzz testing is focused on uncovering security issues. It can include using dedicated fuzz testing tools as well as other security testing tools used to create context specific malicious input. Fuzz testing should focus on self-built protocols, services and parsers.

Examples of fuzz testing tools: AFL, Peach, Defensics.

Examples of other security tools: SQLMap, Burp Suite, OWASP Zap, Radamsa

The fuzz testing is scoped to include: #TODO: describe how and which parts of the input format must be fuzzed#

Fuzz testing is planned to run at least: #TODO: describe how long the tool will be run#

Fuzz testing is conducted with the fuzz testing tool: #TODO: document the selected fuzz testing tool#.

Fuzz testing plans should take the requirements of Appendix B of the ISASecure SDLA-312 Security Development Lifecycle Assessment specification into account. Please refer to the ISASecure SDLA-312 specification for more detail. A summary of these requirements is given here:

* Essential functions of the product must be maintained during the testing, or the test case shall be defined as failed.
* Testing shall be done so that the system is performing its duties at its maximum load.
* Any redundant configuratinos shall be tested both with all redundant units operational or some of the redundant units not operational.
* Tests shall be performed both in a state before authentication and a state after authentication.
* The fuzz test cases shall include specific test traffic characteristics, as described in the requirement SDLA-SVV-3A2-E.
* Fuzz testing arrangements shall ensure that the target of testing is receiving the fuzzed traffic, so that the malformed traffic is not being removed by intervening switches or routers.

=== Documentation and reporting

#TODO: Add a link or an attachment to the detailed test plan and test results, for example to a test management system or to automated tests. If you're tracking manual testing in this tool, then describe the test plan and the test results here.#

== Version history

[cols="1,1,3"]
|===============
|Version | Date | Changes/Author

| 0.1
| 2024-01-01
| XYZ changed by N.N.

|===============

=== Identified security issues

{{#createCards}}
  "template": "secdeva/templates/securityIssue",
  "buttonLabel": "Create a new security issue"
{{/createCards}}

{{#report}}
  "name": "secdeva/reports/securityIssueList"
{{/report}}

=== Notes

#TODO Add any notes about this review#