== Introduction

This is a periodic review for secure development. It is conducted to find out the current state of security work and to plan the security work for the next periods.

== Review checklist

=== Security Issue Status

Check that there are no *Open* security issues or *Analyzed* security issues created over 3 months ago.

Use the checklist in the Appendix A below.
__The list of Security Issues that require attention __should be empty


* [ ] OK
* [ ] Not OK

Comments, links:

=== Security Tool Status

Check that the security issues in all the security testing tools such as static code analyzers and vulnerability tracking tools have been managed.

The issues from these tools should be reported as security issues and managed according to the secure development process.

* [ ] OK
* [ ] Not OK

Comments, links:

=== Security Issue Communication

For each known Security Issue that has not yet been tracked to closure but that affects a released product version or a product version that is currently in use, check that the issue and possible user mitigation strategies and associated risks have been documented to users, or that there is a justified reason not to communicate the issue to product users.

Check that all such Security Issues that identify a vulnerability in a component, including in an open source component, which is integrated in the product, have been reported to the person or entity maintaining the component.

* [ ] OK
* [ ] Not OK

Comments, links:

=== Secure development tasks

All Secure development tasks should have be *OK* or *Not Required* and reviewed within the past *6 months*

* If there are controls in the *Open state*, then plan how they will be scoped, or in other words decided whether they are required
* If there are secure development tasks that are required but not yet OK, then plan the work to perform these controls
* If there are controls that are OK or that are not required, but that have not been reviewed recently enough, then plan when these secure development tasks can be reviewed and updated.

This can be marked as OK if the missing actions are planned.

Use the checklist in the Appendix A below: +
_The list of Secure development tasks that require attention_ should be empty

* [ ] OK
* [ ] Not OK

Comments, links:

=== Composite components

Check that a similar periodic review has been successfully conducted for any composite components recently enough.

See Appendix B.

* [ ] OK or Not Applicable
* [ ] Not OK

Comments, links:

== Conclusion

#TODO: add here a conclusion. The review can be accepted, if the current state of cybersecurity management is known and the required actions have been planned.#

== Action items

* #TODO: add action items#

== Appendix A: Review checklist

* #TODO: Add here a way to see the current state of cybersecurity management in the development project. For example, this could be a Confluence macro that includes a reusable Review checklist. The checklist should include#

* #Security Issues from the issue tracker that affect this release and that have not been tracked to closure#
* #Secure development tasks that are in an acceptable state (reviewed recently enough and either OK or Not Required)#
* #Secure development tasks that require attention: either not yet scoped, required but not yet done, done but not completely acceptable, or expired because of not having been reviewed recently enough#

== Appendix B: Periodic reviews of composite components

* #TODO: add here links or a macro that shows the periodic reviews of composite components#

== Version history

[cols="1,1,3"]
|===============
|Version | Date | Changes/Author

| 0.1
| 2024-01-01
| XYZ changed by N.N.

|===============

{{#createCards}}
  "template": "secdeva/templates/securityIssue",
  "buttonLabel": "Create a new security issue"
{{/createCards}}

{{#report}}
  "name": "secdeva/reports/securityIssueList"
{{/report}}