== Introduction

This document records a review of the use of cryptography in the development project.

== Use cases for cryptography

#TODO: Describe the use cases here, or add a link to documentation.#

NOTE: Notice that the use of cryptograpy must be planned in the light of the expected usage period. Select such algorithms and key lengths that are expected to be applicable during the usage period and as new technologies such as quantum computing become available.

=== #TODO: Title of use case 1#

Use case:: #TODO: describe the use case#
Expected usage period:: #TODO: describe the expected usage period of the protected information#
References:: #TODO: add references that justify the use of cryptography and the selected algorithms, key lengths, key management arrangements#
Algorithms:: #TODO: describe the cryptographic algorithms#
Key length:: #TODO: describe the length of cryptographic keys#
Roles and responsibilities:: #TODO: describe any human user roles and their responsibilities related to this use case#
Key management:: #TODO: add a link or a description of how keys are managed. This includes how they are created, exchanged, stored, access controlled, protected, renewed, revoked, and deleted.#

In this use case, cryptography is used properly and effectively, and the algorithms, key lengths and key management arrangements are up to date and suitable for the use case and the expected usage period:

* [ ] OK
* [ ] Not OK
* [ ] Not applicable

=== #TODO: Title of use case 2#

Use case:: #TODO: describe the use case#
Expected usage period:: #TODO: describe the expected usage period of the protected information#
References:: #TODO: add references that justify the use of cryptography and the selected algorithms, key lengths, key management arrangements#
Algorithms:: #TODO: describe the cryptographic algorithms#
Key length:: #TODO: describe the length of cryptographic keys#
Roles and responsibilities:: #TODO: describe any human user roles and their responsibilities related to this use case#
Key management:: #TODO: add a link or a description of how keys are managed. This includes how they are created, exchanged, stored, access controlled, protected, renewed, revoked, and deleted.#

In this use case, cryptography is used properly and effectively, and the algorithms, key lengths and key management arrangements are up to date and suitable for the use case and the expected usage period:

* [ ] OK
* [ ] Not OK
* [ ] Not applicable

== Review notes

#TODO: if applicable, add a link or an attachment to external systems for more information or evidence.#

#TODO: Describe any notes and remarks about the review here#

== Version history

[cols="1,1,3"]
|===============
|Version | Date | Changes/Author

| 0.1
| 2024-01-01
| XYZ changed by N.N.

|===============

== Identified security issues from this review

{{#createCards}}
  "template": "secdeva/templates/securityIssue",
  "buttonLabel": "Create a new security issue"
{{/createCards}}

{{#report}}
  "name": "secdeva/reports/securityIssueList"
{{/report}}

