This document describes how assets are managed at #Company#.

== Introduction

An asset in anything that has value to the organisation and therefore requires protection.
Asset can be divided into two categories:

* *Primary Assets*: Core business processes, functions and services;
Information and Data servicing business processes and/or activities of the organisation

* *Supporting Assets*: Hardware, devices and equipment, software and applications, roles,
locations and utilities, organisational infrastructure (e.g. policies, procedures and supporting ICT services)

== Roles and responsibilities

[width="100%",cols="5,7,15",options="header"]
|=========================================================
|Role |Person |Responsibilities

|Business Process Owner
|Defined in Roles and Responsibilities document
a|
* Ensures critical assets with their dependencies are identified and recorded to Asset Inventory

|Asset Owner  |Defined per asset in Asset Inventory
a|
* Determines the value of an asset to the organization.

* Ensures assets are sufficiently protected regardless of their location by identifying and mitigating information security risks related to asset

|=========================================================

== Process description

Asset are recorded to Asset Register. If assets (with relevant details) for some categories are already recorded in some other tool, it is enough to add link for reference.


=== STEP 1: Identify primary assets, asset owners and locations (incl. backups)

. Core Business Processes, Functions and Services

. Critical Information/Data (including locations and backups) in all forms (storage, transmission etc) that is of value


=== STEP 2: Identify supporting assets, asset owners and locations

. Information systems

. Suppliers

. Information/Data (including locations and backups) in all forms (storage, transmission etc) that is of value

. Hardware, devices and equipment

=== STEP 3: Classify assets

Each asset category has their own classification/valuation scheme. All assets are classified at least from the following perspectives:

* *Criticality for operations*: High, Medium, Low

* *Risk evaluation needed*: Yes, No

Risk evaluation is mandatory for assets that are critical for operations (Criticality for operations: High), but can also been conducted for non-critical assets, if justifiable (e.g. from brand-protection perspective).

Additionally, information/Data and Information systems are classified at least against the following aspects:

* *Confidentiality*: High (Confidential), Medium (Internal), Low (Public)

* *Integrity*: High (unauthorised changes have significant business impacts), Medium (some changes are tolerable), Low (integrity not relevant for decisions/business)

* *Availability*: High (days), Medium (weeks), Low (months)

* *Contains personal information*: Sensitive, Regular, None

Additional attributes can be specified in Asset Inventory per asset type as needed.

*Note*: If personal data is involved, related processing activities shall be documented into Records of Processing Activities (ROPA).

=== STEP 4: Protect and maintain assets

Asset owner is responsible for ensuring that risks related to their asset are identified as needed and their assets are sufficiently protected and maintained.

Risks related to most important assets are managed in accordance with the Risk Management process.

=== STEP 5: Asset disposal

When assets are no longer needed, they are disposed-off in a secure manner. More detailed device asset disposal principles are covered in IT documentation.

== Document/Process Maintenance and enforcement

Asset inventory is reviewed at least yearly as part of quartal security reviews.

== Related documents/processes

* Risk management process

== Relevant requirements/controls

Most relevant ISO27001 controls are:

* ISO/IEC 27001:2022 – Annex A: 5.9: Inventory of information and other associated assets

* ISO/IEC 27001:2022 – Annex A: 7.13: Equipment maintenance

* ISO/IEC 27001:2022 – Annex A: 7.14: Secure disposal or re-use of equipment


Other controls related to asset management, but not directly covered in this document:

* ISO/IEC 27001:2022 – Annex A: 5.10: Acceptable use of information and other associated assets

* ISO/IEC 27001:2022 – Annex A: 5.11: Return of assets

* ISO/IEC 27001:2022 – Annex A: 5.14: Information transfer

* ISO/IEC 27001:2022 – Annex A: 5.33: Protection of records

* ISO/IEC 27001:2022 – Annex A: 5.37: Documented operating procedures

* ISO/IEC 27001:2022 – Annex A: 6.5: Responsibilities after termination or change of employment

* ISO/IEC 27001:2022 – Annex A: 6.7: Remote working

* ISO/IEC 27001:2022 – Annex A: 7.3: Securing offices, rooms and facilities

* ISO/IEC 27001:2022 – Annex A: 7.8: Equipment siting and protection

* ISO/IEC 27001:2022 – Annex A: 7.9: Security of assets off-premises

* ISO/IEC 27001:2022 – Annex A: 7.9: Storage media

* ISO/IEC 27001:2022 – Annex A: 8.1: User endpoint devices

* ISO/IEC 27001:2022 – Annex A: 8.14: Redundancy of information processing facilities


== References

* link:https://www.enisa.europa.eu/publications/interoperable-eu-risk-management-toolbox[https://www.enisa.europa.eu/publications/interoperable-eu-risk-management-toolbox]

* link:https://www.enisa.europa.eu/publications/2023-interoperable-eu-rm-toolbox/eu-rm-toolbox-library-02-assets-mappings.xlsx[https://www.enisa.europa.eu/publications/2023-interoperable-eu-rm-toolbox/eu-rm-toolbox-library-02-assets-mappings.xlsx]


== Version history

[cols="1,1,3"]
|===============
|Version | Date | Changes/Author

| 1.0
| #TODO <add date>#
| First version created by #N.N#

|===============

== Reviews

{{#createCards}}
    "template": "base/templates/reviewTask",
    "buttonLabel": "Add new review task"
{{/createCards}}

{{#report}}
  "name": "base/reports/childrenTable"
{{/report}}