== Context diagram

{{#graph}}
  "model": "secdeva/graphModels/dataflow",
  "view": "secdeva/graphViews/context",
  "layout": "LR"
{{/graph}}

== Detailed diagram

{{#graph}}
  "model": "secdeva/graphModels/dataflow",
  "view": "secdeva/graphViews/all",
  "layout": "LR"
{{/graph}}

== Top-level elements

Trust boundary:: A trust boundary is a boundary between different trust zone levels.

{{#createCards}}
    "buttonLabel": "Create a trust boundary",
    "template": "secdeva/templates/trustBoundary"
{{/createCards}}

External entity:: An external entity is a source from which information flows into the system, or a recipients of information leaving the system

{{#createCards}}
  "buttonLabel": "Create an external entity",
  "template": "secdeva/templates/external"
{{/createCards}}

Person:: A person is a user, an administrator or another human stakeholder. A special case of an external entity.

{{#createCards}}
  "buttonLabel": "Create a person",
  "template": "secdeva/templates/person"
{{/createCards}}

Process:: A process represents an activity that the system carries out.

{{#createCards}}
  "buttonLabel": "Create a process",
  "template": "secdeva/templates/process"
{{/createCards}}

Data store:: A data store stores information. For example, a database or a file.

{{#createCards}}
  "buttonLabel": "Create a data store",
  "template": "secdeva/templates/dataStore"
{{/createCards}}

